//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:38:17 PM CST 
//


package deskera.fintech.oauth;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the deskera.fintech.oauth package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OAuthToken_QNAME = new QName("http://com.citi.citiconnect/services/types/oauthtoken/v1", "oAuthToken");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: deskera.fintech.oauth
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OAuthTokenType }
     * 
     */
    public OAuthTokenType createOAuthTokenType() {
        return new OAuthTokenType();
    }

    /**
     * Create an instance of {@link UserDetailsType }
     * 
     */
    public UserDetailsType createUserDetailsType() {
        return new UserDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OAuthTokenType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OAuthTokenType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/oauthtoken/v1", name = "oAuthToken")
    public JAXBElement<OAuthTokenType> createOAuthToken(OAuthTokenType value) {
        return new JAXBElement<OAuthTokenType>(_OAuthToken_QNAME, OAuthTokenType.class, null, value);
    }

}
