//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:40:43 PM CST 
//


package deskera.fintech.statret;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faultDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faultDetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="correlationId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="errorCode" type="{http://com.citi.citiconnect/services/types/citiconnect/v1}ErrorCodeTypeEnum"/&gt;
 *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="errorSource" type="{http://com.citi.citiconnect/services/types/citiconnect/v1}ErrorSourceTypeEnum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faultDetailType", propOrder = {
    "correlationId",
    "errorCode",
    "errorMsg",
    "errorSource"
})
@XmlSeeAlso({
    InvalidOAuthTokenFaultDetail.class,
    AccessDeniedFaultDetail.class,
    BeneficiaryNotFoundDetail.class,
    DebtorAccountNotFoundDetail.class,
    UnsupportedPaymentMethodTypeDetail.class,
    FailedToProcessPaymentDetail.class,
    PaymentNotFoundFaultDetail.class,
    UnknownUserFaultDetail.class,
    StatementEmptyFaultDetail.class,
    StatementNotFoundFaultDetail.class,
    StatementNotReadyFaultDetail.class,
    NotEntitledToStatementRetrievalFaultDetail.class
})
public class FaultDetailType {

    @XmlElement(required = true)
    protected String correlationId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ErrorCodeTypeEnum errorCode;
    @XmlElement(required = true)
    protected String errorMsg;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ErrorSourceTypeEnum errorSource;

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorCodeTypeEnum }
     *     
     */
    public ErrorCodeTypeEnum getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorCodeTypeEnum }
     *     
     */
    public void setErrorCode(ErrorCodeTypeEnum value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

    /**
     * Gets the value of the errorSource property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorSourceTypeEnum }
     *     
     */
    public ErrorSourceTypeEnum getErrorSource() {
        return errorSource;
    }

    /**
     * Sets the value of the errorSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorSourceTypeEnum }
     *     
     */
    public void setErrorSource(ErrorSourceTypeEnum value) {
        this.errorSource = value;
    }

}
