//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:40:43 PM CST 
//


package deskera.fintech.statret;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogInRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogInRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="certSerialNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="certDistinguishedName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sourceSystemUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sourceSystemClientName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://com.citi.citiconnect/services/types/oauthtoken/v1}oAuthToken"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogInRequestType", propOrder = {
    "certSerialNo",
    "certDistinguishedName",
    "sourceSystemUserName",
    "sourceSystemClientName",
    "oAuthToken"
})
public class LogInRequestType {

    protected String certSerialNo;
    protected String certDistinguishedName;
    protected String sourceSystemUserName;
    protected String sourceSystemClientName;
    @XmlElement(namespace = "http://com.citi.citiconnect/services/types/oauthtoken/v1", required = true)
    protected OAuthTokenType oAuthToken;

    /**
     * Gets the value of the certSerialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertSerialNo() {
        return certSerialNo;
    }

    /**
     * Sets the value of the certSerialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertSerialNo(String value) {
        this.certSerialNo = value;
    }

    /**
     * Gets the value of the certDistinguishedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertDistinguishedName() {
        return certDistinguishedName;
    }

    /**
     * Sets the value of the certDistinguishedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertDistinguishedName(String value) {
        this.certDistinguishedName = value;
    }

    /**
     * Gets the value of the sourceSystemUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemUserName() {
        return sourceSystemUserName;
    }

    /**
     * Sets the value of the sourceSystemUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemUserName(String value) {
        this.sourceSystemUserName = value;
    }

    /**
     * Gets the value of the sourceSystemClientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemClientName() {
        return sourceSystemClientName;
    }

    /**
     * Sets the value of the sourceSystemClientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemClientName(String value) {
        this.sourceSystemClientName = value;
    }

    /**
     * Contains the contents of the OAuth token 'as is' from calling client (if applicable)
     * 
     * @return
     *     possible object is
     *     {@link OAuthTokenType }
     *     
     */
    public OAuthTokenType getOAuthToken() {
        return oAuthToken;
    }

    /**
     * Sets the value of the oAuthToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link OAuthTokenType }
     *     
     */
    public void setOAuthToken(OAuthTokenType value) {
        this.oAuthToken = value;
    }

}
