//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:40:43 PM CST 
//


package deskera.fintech.statret;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogInResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogInResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="entitlements" type="{http://com.citi.citiconnect/services/types/citiconnect/v1}EntitlementsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogInResponseType", propOrder = {
    "entitlements"
})
public class LogInResponseType {

    @XmlElement(required = true)
    protected EntitlementsType entitlements;

    /**
     * Gets the value of the entitlements property.
     * 
     * @return
     *     possible object is
     *     {@link EntitlementsType }
     *     
     */
    public EntitlementsType getEntitlements() {
        return entitlements;
    }

    /**
     * Sets the value of the entitlements property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitlementsType }
     *     
     */
    public void setEntitlements(EntitlementsType value) {
        this.entitlements = value;
    }

}
