//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:40:43 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package deskera.fintech.statret;
