//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:40:43 PM CST 
//


package deskera.fintech.statret;

import javax.activation.DataHandler;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatementRetrievalResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementRetrievalResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="statementId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fileCheckSum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="statementStream" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementRetrievalResponseType", namespace = "http://com.citi.citiconnect/services/types/attachments/v1", propOrder = {
    "statementId",
    "fileCheckSum",
    "statementStream"
})
public class StatementRetrievalResponseType {

    @XmlElement(required = true)
    protected String statementId;
    @XmlElement(required = true)
    protected String fileCheckSum;
    @XmlElement(required = true)
    @XmlMimeType("application/xop")
    protected DataHandler statementStream;

    /**
     * Gets the value of the statementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatementId() {
        return statementId;
    }

    /**
     * Sets the value of the statementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatementId(String value) {
        this.statementId = value;
    }

    /**
     * Gets the value of the fileCheckSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileCheckSum() {
        return fileCheckSum;
    }

    /**
     * Sets the value of the fileCheckSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileCheckSum(String value) {
        this.fileCheckSum = value;
    }

    /**
     * Gets the value of the statementStream property.
     * 
     * @return
     *     possible object is
     *     {@link DataHandler }
     *     
     */
    public DataHandler getStatementStream() {
        return statementStream;
    }

    /**
     * Sets the value of the statementStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHandler }
     *     
     */
    public void setStatementStream(DataHandler value) {
        this.statementStream = value;
    }

}
