//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:37:49 PM CST 
//


package deskera.fintech.payinit;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the deskera.fintech.payinit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CorrelationId_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "correlationId");
    private final static QName _LogInRequest_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "logInRequest");
    private final static QName _LogInResponse_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "logInResponse");
    private final static QName _PaymentInitiationResponse_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "paymentInitiationResponse");
    private final static QName _LogOutRequest_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "logOutRequest");
    private final static QName _LogOutResponse_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "logOutResponse");
    private final static QName _FaultDetail_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "faultDetail");
    private final static QName _Base64Payload_QNAME = new QName("http://com.citi.citiconnect/services/types/citiconnect/v1", "base64Payload");
    private final static QName _OAuthToken_QNAME = new QName("http://com.citi.citiconnect/services/types/oauthtoken/v1", "oAuthToken");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: deskera.fintech.payinit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogInRequestType }
     * 
     */
    public LogInRequestType createLogInRequestType() {
        return new LogInRequestType();
    }

    /**
     * Create an instance of {@link LogInResponseType }
     * 
     */
    public LogInResponseType createLogInResponseType() {
        return new LogInResponseType();
    }

    /**
     * Create an instance of {@link PaymentInitiationRequest }
     * 
     */
    public PaymentInitiationRequest createPaymentInitiationRequest() {
        return new PaymentInitiationRequest();
    }

    /**
     * Create an instance of {@link PayloadHeadersType }
     * 
     */
    public PayloadHeadersType createPayloadHeadersType() {
        return new PayloadHeadersType();
    }

    /**
     * Create an instance of {@link LogOutRequestType }
     * 
     */
    public LogOutRequestType createLogOutRequestType() {
        return new LogOutRequestType();
    }

    /**
     * Create an instance of {@link LogOutResponseType }
     * 
     */
    public LogOutResponseType createLogOutResponseType() {
        return new LogOutResponseType();
    }

    /**
     * Create an instance of {@link UnknownUserFaultDetail }
     * 
     */
    public UnknownUserFaultDetail createUnknownUserFaultDetail() {
        return new UnknownUserFaultDetail();
    }

    /**
     * Create an instance of {@link FaultDetailType }
     * 
     */
    public FaultDetailType createFaultDetailType() {
        return new FaultDetailType();
    }

    /**
     * Create an instance of {@link PaymentNotFoundFaultDetail }
     * 
     */
    public PaymentNotFoundFaultDetail createPaymentNotFoundFaultDetail() {
        return new PaymentNotFoundFaultDetail();
    }

    /**
     * Create an instance of {@link FailedToProcessPaymentDetail }
     * 
     */
    public FailedToProcessPaymentDetail createFailedToProcessPaymentDetail() {
        return new FailedToProcessPaymentDetail();
    }

    /**
     * Create an instance of {@link UnsupportedPaymentMethodTypeDetail }
     * 
     */
    public UnsupportedPaymentMethodTypeDetail createUnsupportedPaymentMethodTypeDetail() {
        return new UnsupportedPaymentMethodTypeDetail();
    }

    /**
     * Create an instance of {@link DebtorAccountNotFoundDetail }
     * 
     */
    public DebtorAccountNotFoundDetail createDebtorAccountNotFoundDetail() {
        return new DebtorAccountNotFoundDetail();
    }

    /**
     * Create an instance of {@link BeneficiaryNotFoundDetail }
     * 
     */
    public BeneficiaryNotFoundDetail createBeneficiaryNotFoundDetail() {
        return new BeneficiaryNotFoundDetail();
    }

    /**
     * Create an instance of {@link AccessDeniedFaultDetail }
     * 
     */
    public AccessDeniedFaultDetail createAccessDeniedFaultDetail() {
        return new AccessDeniedFaultDetail();
    }

    /**
     * Create an instance of {@link InvalidOAuthTokenFaultDetail }
     * 
     */
    public InvalidOAuthTokenFaultDetail createInvalidOAuthTokenFaultDetail() {
        return new InvalidOAuthTokenFaultDetail();
    }

    /**
     * Create an instance of {@link PayloadHeaderType }
     * 
     */
    public PayloadHeaderType createPayloadHeaderType() {
        return new PayloadHeaderType();
    }

    /**
     * Create an instance of {@link EntitlementsType }
     * 
     */
    public EntitlementsType createEntitlementsType() {
        return new EntitlementsType();
    }

    /**
     * Create an instance of {@link EntitlementType }
     * 
     */
    public EntitlementType createEntitlementType() {
        return new EntitlementType();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link OAuthTokenType }
     * 
     */
    public OAuthTokenType createOAuthTokenType() {
        return new OAuthTokenType();
    }

    /**
     * Create an instance of {@link UserDetailsType }
     * 
     */
    public UserDetailsType createUserDetailsType() {
        return new UserDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "correlationId")
    public JAXBElement<String> createCorrelationId(String value) {
        return new JAXBElement<String>(_CorrelationId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogInRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogInRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "logInRequest")
    public JAXBElement<LogInRequestType> createLogInRequest(LogInRequestType value) {
        return new JAXBElement<LogInRequestType>(_LogInRequest_QNAME, LogInRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogInResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogInResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "logInResponse")
    public JAXBElement<LogInResponseType> createLogInResponse(LogInResponseType value) {
        return new JAXBElement<LogInResponseType>(_LogInResponse_QNAME, LogInResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "paymentInitiationResponse")
    public JAXBElement<byte[]> createPaymentInitiationResponse(byte[] value) {
        return new JAXBElement<byte[]>(_PaymentInitiationResponse_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogOutRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogOutRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "logOutRequest")
    public JAXBElement<LogOutRequestType> createLogOutRequest(LogOutRequestType value) {
        return new JAXBElement<LogOutRequestType>(_LogOutRequest_QNAME, LogOutRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogOutResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LogOutResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "logOutResponse")
    public JAXBElement<LogOutResponseType> createLogOutResponse(LogOutResponseType value) {
        return new JAXBElement<LogOutResponseType>(_LogOutResponse_QNAME, LogOutResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultDetailType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FaultDetailType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "faultDetail")
    public JAXBElement<FaultDetailType> createFaultDetail(FaultDetailType value) {
        return new JAXBElement<FaultDetailType>(_FaultDetail_QNAME, FaultDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/citiconnect/v1", name = "base64Payload")
    public JAXBElement<byte[]> createBase64Payload(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Payload_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OAuthTokenType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OAuthTokenType }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.citi.citiconnect/services/types/oauthtoken/v1", name = "oAuthToken")
    public JAXBElement<OAuthTokenType> createOAuthToken(OAuthTokenType value) {
        return new JAXBElement<OAuthTokenType>(_OAuthToken_QNAME, OAuthTokenType.class, null, value);
    }

}
