//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:37:49 PM CST 
//


package deskera.fintech.payinit;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="payloadType" type="{http://com.citi.citiconnect/services/types/citiconnect/v1}PayloadTypeEnum"/&gt;
 *         &lt;element name="payloadHeaders" type="{http://com.citi.citiconnect/services/types/citiconnect/v1}PayloadHeadersType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="payload" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "payloadType",
    "payloadHeaders",
    "payload"
})
@XmlRootElement(name = "paymentInitiationRequest")
public class PaymentInitiationRequest {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PayloadTypeEnum payloadType;
    protected List<PayloadHeadersType> payloadHeaders;
    @XmlElement(required = true)
    protected byte[] payload;

    /**
     * Gets the value of the payloadType property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadTypeEnum }
     *     
     */
    public PayloadTypeEnum getPayloadType() {
        return payloadType;
    }

    /**
     * Sets the value of the payloadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadTypeEnum }
     *     
     */
    public void setPayloadType(PayloadTypeEnum value) {
        this.payloadType = value;
    }

    /**
     * Gets the value of the payloadHeaders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payloadHeaders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayloadHeaders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayloadHeadersType }
     * 
     * 
     */
    public List<PayloadHeadersType> getPayloadHeaders() {
        if (payloadHeaders == null) {
            payloadHeaders = new ArrayList<PayloadHeadersType>();
        }
        return this.payloadHeaders;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPayload(byte[] value) {
        this.payload = value;
    }

}
